name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [auth-service, passport-service, document-service, notification-service]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Install
        run: npm ci
        env:
          NODE_ENV: test

      - name: Lint (if available)
        run: npm run lint --if-present

      - name: Test (if available)
        run: npm test --if-present

      - name: Build (if available)
        run: npm run build --if-present
